name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY] "
labels: ["security", "vulnerability", "urgent"]
assignees: ["vekis11"]

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ SECURITY VULNERABILITY REPORT ⚠️**
        
        This form is for reporting security vulnerabilities. Please do not use this for general bug reports.
        
        **Important**: Security vulnerabilities are taken very seriously. Please follow responsible disclosure practices.

  - type: dropdown
    id: severity
    attributes:
      label: Vulnerability Severity
      description: How severe is this security vulnerability?
      options:
        - Low - Minor security issue
        - Medium - Moderate security risk
        - High - Significant security risk
        - Critical - Severe security vulnerability
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this vulnerability?
      options:
        - Frontend (React)
        - Backend (Node.js)
        - Database (MongoDB)
        - Authentication (JWT)
        - API Endpoints
        - Security Integrations
        - CI/CD Pipeline
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability.
      placeholder: Describe the security vulnerability in detail...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Data exposure
        - Unauthorized access
        - Privilege escalation
        - Code execution
        - Information disclosure
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
        4. Observe the vulnerability
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Windows 10, macOS, Ubuntu]
        - Node.js version: [e.g. 18.17.0]
        - Browser: [e.g. Chrome 119, Firefox 118]
        - MongoDB version: [e.g. 6.0.8]
        - Application version: [e.g. 1.0.0]
      value: |
        - OS: 
        - Node.js version: 
        - Browser: 
        - MongoDB version: 
        - Application version: 
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: If applicable, provide a proof of concept or exploit code
      placeholder: Provide proof of concept code or exploit details...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability, please provide them
      placeholder: Describe any suggested fixes or mitigations...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant references, CVE numbers, or related vulnerabilities
      placeholder: |
        - CVE-XXXX-XXXX
        - OWASP Top 10 reference
        - Related security advisories
        - Other references

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: I understand and agree to responsible disclosure practices
      options:
        - label: I agree to responsible disclosure practices
          required: true
        - label: I will not publicly disclose this vulnerability until it is fixed
          required: true
        - label: I understand this may take time to investigate and fix
          required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How should we contact you for follow-up? (Optional)
      placeholder: |
        - Email: your-email@example.com
        - GitHub: @your-username
        - Other: Please specify
